
print("************")
print("File: BenjaminFeedback.py")
print("I like the Github Workshop so far and the Algortimic Thinking Workshop was fun aswell")
print("************")
print("************")
print("File: feedback.1aurenz.py")
print(""" works

yay
""")
print("************")
print("************")
print("File: GitGood.py")
print("Hello")
print("I liked the presentation")
print("Please insert one line of text on a slide at a time next time")
print("One can read it better")

print("************")
print("************")
print("File: jurij.py")
print('Coole Rabbit-Story am Anfang. :)')
print('Viel Text auf einer Folie')

print("************")
print("************")
print("File: luemfeedback.py")
print("The introduction with the bunny story is pretty useful to depict the problem with collaboration in coding and the usecase of Git to solve that")
print("************")
print("************")
print("File: luemtest.py")
print("The introduction with the bunny story is pretty useful for depict the problem with collaboration in coding and the usecase of Git to solve that")
print("************")
print("************")
print("File: phil.py")
print("Hello there!")
print("Nice Workshop! The content was well explained and easy to understand.")
print("************")
print("************")
print("File: viktorfeedback.py")
print("POSITIV: Sehr verständlich gut erklärt und auch, die Beispiele sind sehr kreativ gestaltet sodass man es Nachvollziehen kann. Bildlich erklärt ")
print("NEGATIV: Workshop kommt ein wenig zu spät. Hätten wir ihn früher wäre einiges schneller vorangegangen")

print("************")
print("************")
print("File: workshoptestMH.py")
print("The workshop is simple and to the point, but offers vital information which will be relevant for future projects. There have been situations in which I've struggled with git, and the step by step guide has helped clear things up for me.")
print("************")